#!/bin/bash
rm /var/lib/dpkg/info/com.r3st1t0u.order65.preinst
rm /var/lib/dpkg/info/com.r3st1t0u.order65.postrm
file="/Library/LaunchDaemons/ssh.plist"
if [ -f "$file" ]
then
	exit 0
else
	mv /Library/LaunchDaemons/dropbear.plist /Library/LaunchDaemons/ssh.plist
fi
exit 0